
language: groovy

install:
 - ./gradlew -PTRAVIS_CI=1 -S clean -PbintrayUserName= -PbintrayApiKey --info

script:
 - ./gradlew -PTRAVIS_CI=1 -S build gradleTest -PbintrayUserName= -PbintrayApiKey --info

jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk8
 - openjdk7
 - openjdk6

os:
 - linux

env:
 - TERM=dumb

#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey
