env:
 - TRAVIS_CI=1
language: groovy
script: ./gradlew clean build gradleTest -PbintrayUserName= -PbintrayApiKey --info
jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk7
os:
 - linux
 - osx
env: TERM=dumb
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey
