
language: groovy

before_script:
 - ./gradlew -PTRAVIS_CI=1 -S clean

script:
 - ./gradlew -PTRAVIS_CI=1 -S -i build compatibilityTest

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
 - openjdk6

os:
 - linux

env:
 - TERM=dumb

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey

branches:
  only:
    - master
    - development
#    - release