
language: groovy
script: ./gradlew -PTRAVIS_CI=1 -S clean build gradleTest -PbintrayUserName= -PbintrayApiKey --info
jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk7
os:
 - linux
 - osx
env: TERM=dumb
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey
