
language: groovy

sudo: required

before_script:
 - ./gradlew -S clean --console=plain

install: true

script:
 - ./gradlew -S -i --no-build-cache --console=plain assemble
 - ./gradlew -i --no-build-cache --console=plain test
 - ./gradlew -i --no-build-cache --console=plain integrationTest
 - ./gradlew -i --no-build-cache --console=plain compatibilityTest

jdk:
 - oraclejdk8

os:
 - linux
# osx_image: xcode7.3

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master
    - development
#    - release
